# Generated by Django 5.1.4 on 2025-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Duration',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
